
    create table ai_chat_messages (
        ai_chat_message_id bigint generated by default as identity,
        ai_chat_session_id bigint not null,
        created_at timestamp(6) not null,
        sender_type varchar(20) not null,
        message_text TEXT not null,
        primary key (ai_chat_message_id)
    );

    create table ai_chat_sessions (
        ai_chat_session_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        patient_id bigint,
        session_type varchar(30) not null,
        summary TEXT,
        primary key (ai_chat_session_id)
    );

    create table ai_specialty_suggestions (
        accepted_by_patient boolean not null,
        confidence_score numeric(5,2),
        ai_chat_session_id bigint not null,
        created_at timestamp(6) not null,
        department_id bigint,
        patient_id bigint,
        suggestion_id bigint generated by default as identity,
        explanation TEXT,
        symptoms_text TEXT,
        primary key (suggestion_id)
    );

    create table appointment_slots (
        end_time time(6) not null,
        start_time time(6) not null,
        locked_by_patient_id bigint,
        locked_until timestamp(6),
        schedule_id bigint not null,
        slot_id bigint generated by default as identity,
        status varchar(255) not null,
        primary key (slot_id)
    );

    create table appointments (
        appointment_date date not null,
        deposit_amount numeric(38,2) not null,
        end_time time(6) not null,
        reminder_sent boolean not null,
        start_time time(6) not null,
        appointment_id bigint generated by default as identity,
        cancelled_at timestamp(6),
        cancelled_by bigint,
        checked_in_at timestamp(6),
        checked_in_by bigint,
        created_at timestamp(6) not null,
        created_by bigint,
        department_id bigint not null,
        doctor_id bigint not null,
        patient_id bigint not null,
        rescheduled_from_id bigint,
        slot_id bigint,
        updated_at timestamp(6) not null,
        booking_type varchar(20) not null,
        appointment_code varchar(30) not null unique,
        status varchar(30) not null,
        cancellation_reason TEXT,
        initial_symptoms TEXT,
        no_show_reason TEXT,
        reason_for_visit TEXT,
        primary key (appointment_id)
    );

    create table articles (
        article_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        created_by bigint,
        published_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(20) not null,
        slug varchar(1000) not null unique,
        title varchar(1000) not null,
        content TEXT not null,
        thumbnail_url TEXT,
        primary key (article_id)
    );

    create table audit_logs (
        audit_log_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        record_id bigint,
        user_id bigint,
        action varchar(100) not null,
        ip_address varchar(100),
        table_name varchar(100),
        user_agent TEXT,
        new_value jsonb,
        old_value jsonb,
        primary key (audit_log_id)
    );

    create table consultation_sessions (
        appointment_id bigint not null unique,
        completed_at timestamp(6),
        consultation_id bigint generated by default as identity,
        created_at timestamp(6) not null,
        doctor_id bigint not null,
        patient_id bigint not null,
        started_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(30) not null,
        primary key (consultation_id)
    );

    create table departments (
        created_at timestamp(6) not null,
        department_id bigint generated by default as identity,
        status varchar(20) not null,
        department_name varchar(150) not null unique,
        description TEXT,
        primary key (department_id)
    );

    create table doctor_leave_requests (
        end_time time(6) not null,
        leave_date date not null,
        start_time time(6) not null,
        approved_at timestamp(6),
        approved_by bigint,
        created_at timestamp(6) not null,
        doctor_id bigint not null,
        from_datetime timestamp(6) not null,
        leave_request_id bigint generated by default as identity,
        to_datetime timestamp(6) not null,
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('PENDING','APPROVED','REJECTED')),
        request_type varchar(30) not null check (request_type in ('LEAVE','CHANGE_SCHEDULE')),
        admin_comment TEXT,
        reason TEXT,
        primary key (leave_request_id)
    );

    create table doctor_schedules (
        end_time time(6) not null,
        max_patients integer not null,
        start_time time(6) not null,
        work_date date not null,
        doctor_id bigint not null,
        schedule_id bigint generated by default as identity,
        status varchar(255) not null,
        primary key (schedule_id)
    );

    create table doctors (
        consultation_fee NUMERIC(10,2),
        year_of_birth integer,
        years_of_experience integer,
        created_at timestamp(6) not null,
        department_id bigint,
        doctor_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint not null unique,
        status varchar(20) not null,
        doctor_code varchar(30) not null unique,
        degree varchar(100),
        hometown varchar(150),
        specialization varchar(150),
        biography TEXT,
        primary key (doctor_id)
    );

    create table email_otps (
        consumed boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        otp_id bigint generated by default as identity,
        purpose varchar(30) not null,
        email varchar(255) not null,
        otp_hash varchar(255) not null,
        primary key (otp_id)
    );

    create table invoice_items (
        quantity integer not null,
        total_price numeric(12,2) not null,
        unit_price numeric(12,2) not null,
        invoice_id bigint not null,
        invoice_item_id bigint generated by default as identity,
        reference_id bigint,
        item_type varchar(20) not null,
        item_name varchar(255) not null,
        primary key (invoice_item_id)
    );

    create table invoices (
        discount_amount numeric(12,2) not null,
        final_amount numeric(12,2) not null,
        total_amount numeric(12,2) not null,
        appointment_id bigint,
        created_at timestamp(6) not null,
        created_by bigint,
        invoice_id bigint generated by default as identity,
        paid_at timestamp(6),
        patient_id bigint not null,
        status varchar(20) not null,
        invoice_code varchar(30) not null unique,
        primary key (invoice_id)
    );

    create table lab_request_items (
        lab_request_id bigint not null,
        lab_request_item_id bigint generated by default as identity,
        lab_test_id bigint not null,
        status varchar(20) not null,
        note varchar(500),
        primary key (lab_request_item_id)
    );

    create table lab_requests (
        accepted_at timestamp(6),
        accepted_by bigint,
        completed_at timestamp(6),
        consultation_id bigint not null,
        doctor_id bigint not null,
        lab_request_id bigint generated by default as identity,
        patient_id bigint not null,
        requested_at timestamp(6) not null,
        status varchar(20) not null,
        request_code varchar(30) not null unique,
        note TEXT,
        primary key (lab_request_id)
    );

    create table lab_results (
        entered_at timestamp(6) not null,
        entered_by bigint,
        lab_request_item_id bigint not null unique,
        lab_result_id bigint generated by default as identity,
        result_unit varchar(50),
        normal_range varchar(100),
        result_file_url varchar(500),
        conclusion TEXT,
        result_value TEXT,
        primary key (lab_result_id)
    );

    create table lab_tests (
        price numeric(12,2),
        created_at timestamp(6) not null,
        lab_test_id bigint generated by default as identity,
        status varchar(20) not null,
        test_code varchar(30) not null unique,
        test_name varchar(150) not null,
        description TEXT,
        primary key (lab_test_id)
    );

    create table medical_records (
        follow_up_date date,
        consultation_id bigint not null unique,
        created_at timestamp(6) not null,
        doctor_id bigint not null,
        medical_record_id bigint generated by default as identity,
        patient_id bigint not null,
        updated_at timestamp(6) not null,
        ai_summary TEXT,
        clinical_findings TEXT,
        diagnosis TEXT,
        doctor_note TEXT,
        follow_up_note TEXT,
        symptoms TEXT,
        treatment_plan TEXT,
        voice_input_transcript TEXT,
        primary key (medical_record_id)
    );

    create table medical_services (
        price numeric(12,2) not null,
        created_at timestamp(6) not null,
        service_id bigint generated by default as identity,
        service_type varchar(20) not null,
        status varchar(20) not null,
        service_code varchar(30) not null unique,
        service_name varchar(150) not null,
        description TEXT,
        primary key (service_id)
    );

    create table medicine_batches (
        current_quantity integer not null,
        expiry_date date not null,
        import_price numeric(12,2) not null,
        initial_quantity integer not null,
        manufacture_date date,
        selling_price numeric(12,2) not null,
        batch_id bigint generated by default as identity,
        imported_at timestamp(6) not null,
        imported_by bigint,
        medicine_id bigint not null,
        supplier_id bigint,
        status varchar(20) not null,
        batch_number varchar(100) not null,
        primary key (batch_id)
    );

    create table medicine_stock_alerts (
        is_resolved boolean not null,
        alert_id bigint generated by default as identity,
        batch_id bigint,
        created_at timestamp(6) not null,
        medicine_id bigint not null,
        resolved_at timestamp(6),
        resolved_by bigint,
        alert_type varchar(20) not null,
        message TEXT,
        primary key (alert_id)
    );

    create table medicines (
        created_at timestamp(6) not null,
        medicine_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        status varchar(20) not null,
        medicine_code varchar(30) not null unique,
        unit varchar(50),
        dosage_form varchar(100),
        rxnorm_code varchar(100),
        strength varchar(100),
        medicine_name varchar(150) not null,
        active_ingredient varchar(255),
        description TEXT,
        usage_instructions varchar(255),
        primary key (medicine_id)
    );

    create table notifications (
        is_read boolean not null,
        created_at timestamp(6) not null,
        notification_id bigint generated by default as identity,
        user_id bigint not null,
        type varchar(50) not null,
        message TEXT not null,
        title varchar(255) not null,
        primary key (notification_id)
    );

    create table patients (
        date_of_birth date,
        height_cm float(53),
        weight_kg float(53),
        created_at timestamp(6) not null,
        created_by bigint,
        patient_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        user_id bigint,
        blood_type varchar(10),
        emergency_contact_phone varchar(20),
        gender varchar(20) not null,
        phone varchar(20),
        relationship_to_user varchar(20) not null,
        identity_number varchar(30),
        patient_code varchar(30) not null unique,
        ethnicity varchar(50),
        insurance_number varchar(50),
        occupation varchar(100),
        emergency_contact_name varchar(150),
        full_name varchar(150) not null,
        avatar_url varchar(500),
        address TEXT,
        allergies TEXT,
        current_medications TEXT,
        email varchar(255),
        family_history TEXT,
        lifestyle_habits TEXT,
        medical_history TEXT,
        surgical_history TEXT,
        primary key (patient_id)
    );

    create table payments (
        amount numeric(12,2) not null,
        appointment_id bigint,
        confirmed_by bigint,
        created_at timestamp(6) not null,
        expires_at timestamp(6),
        invoice_id bigint,
        paid_at timestamp(6),
        paid_by bigint,
        payment_id bigint generated by default as identity,
        payment_method varchar(20) not null,
        payment_type varchar(20) not null,
        status varchar(20) not null,
        payment_code varchar(30) not null unique,
        gateway_provider varchar(100),
        gateway_transaction_id varchar(255),
        primary key (payment_id)
    );

    create table permissions (
        permission_id bigint generated by default as identity,
        permission_code varchar(100) not null unique,
        description TEXT,
        primary key (permission_id)
    );

    create table prescription_items (
        quantity integer not null,
        medicine_id bigint not null,
        prescription_id bigint not null,
        prescription_item_id bigint generated by default as identity,
        evening_dose varchar(50),
        morning_dose varchar(50),
        night_dose varchar(50),
        noon_dose varchar(50),
        dosage varchar(255),
        duration varchar(255),
        frequency varchar(255),
        instructions TEXT,
        primary key (prescription_item_id)
    );

    create table prescriptions (
        drug_interaction_checked boolean not null,
        checked_at timestamp(6),
        consultation_id bigint not null,
        created_at timestamp(6) not null,
        dispensed_at timestamp(6),
        doctor_id bigint not null,
        patient_id bigint not null,
        prescription_id bigint generated by default as identity,
        status varchar(20) not null,
        prescription_code varchar(30) not null unique,
        doctor_note TEXT,
        interaction_warning TEXT,
        primary key (prescription_id)
    );

    create table queue_tickets (
        estimated_wait_minutes integer,
        queue_date date not null,
        queue_number integer not null,
        appointment_id bigint not null unique,
        called_at timestamp(6),
        checked_in_at timestamp(6),
        completed_at timestamp(6),
        created_at timestamp(6) not null,
        department_id bigint not null,
        doctor_id bigint not null,
        patient_id bigint not null,
        queue_ticket_id bigint generated by default as identity,
        priority_level varchar(20) not null,
        status varchar(20) not null,
        primary key (queue_ticket_id)
    );

    create table refunds (
        refund_amount numeric(12,2) not null,
        approved_at timestamp(6),
        approved_by bigint,
        completed_at timestamp(6),
        payment_id bigint not null,
        processed_at timestamp(6),
        processed_by bigint,
        refund_id bigint generated by default as identity,
        requested_at timestamp(6) not null,
        requested_by bigint,
        status varchar(20) not null,
        refund_code varchar(30) not null unique,
        refund_method varchar(30),
        bank_account_number varchar(50),
        bank_name varchar(100),
        account_holder_name varchar(150),
        reason TEXT,
        refund_transaction_ref varchar(255),
        reject_reason TEXT,
        primary key (refund_id)
    );

    create table reviews (
        rating integer not null,
        appointment_id bigint,
        created_at timestamp(6) not null,
        doctor_id bigint,
        patient_id bigint not null,
        review_id bigint generated by default as identity,
        status varchar(20) not null,
        comment TEXT,
        primary key (review_id)
    );

    create table role_permissions (
        permission_id bigint not null,
        role_id bigint not null,
        primary key (permission_id, role_id)
    );

    create table roles (
        role_id bigint generated by default as identity,
        role_name varchar(50) not null unique,
        description TEXT,
        primary key (role_id)
    );

    create table stock_transactions (
        quantity integer not null,
        batch_id bigint,
        created_at timestamp(6) not null,
        created_by bigint,
        medicine_id bigint not null,
        reference_id bigint,
        stock_transaction_id bigint generated by default as identity,
        reference_type varchar(30) not null,
        transaction_type varchar(30) not null,
        note TEXT,
        primary key (stock_transaction_id)
    );

    create table suppliers (
        created_at timestamp(6) not null,
        supplier_id bigint generated by default as identity,
        phone varchar(20),
        status varchar(20) not null,
        supplier_name varchar(150) not null,
        address TEXT,
        email varchar(255),
        primary key (supplier_id)
    );

    create table system_settings (
        setting_id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        updated_by bigint,
        setting_key varchar(100) not null unique,
        description TEXT,
        setting_value TEXT,
        primary key (setting_id)
    );

    create table user_roles (
        role_id bigint not null,
        user_id bigint not null,
        primary key (role_id, user_id)
    );

    create table users (
        created_at timestamp(6) not null,
        updated_at timestamp(6) not null,
        user_id bigint generated by default as identity,
        auth_provider varchar(20) not null,
        phone varchar(20),
        status varchar(20) not null,
        full_name varchar(150) not null,
        avatar_url varchar(500),
        email varchar(255) not null unique,
        password_hash varchar(255),
        provider_id varchar(255),
        primary key (user_id)
    );

    create table vital_signs (
        blood_pressure_diastolic integer,
        blood_pressure_systolic integer,
        heart_rate integer,
        height_cm numeric(5,2),
        respiratory_rate integer,
        spo2 integer,
        temperature_c numeric(4,1),
        weight_kg numeric(5,2),
        consultation_id bigint not null,
        measured_at timestamp(6) not null,
        measured_by bigint,
        patient_id bigint not null,
        vital_sign_id bigint generated by default as identity,
        primary key (vital_sign_id)
    );

    alter table if exists ai_chat_messages 
       add constraint FK1p8cmsmrvyfw8jviaalw088sd 
       foreign key (ai_chat_session_id) 
       references ai_chat_sessions;

    alter table if exists ai_chat_sessions 
       add constraint FKb2pdampnria28cx0l922c0fd7 
       foreign key (patient_id) 
       references patients;

    alter table if exists ai_specialty_suggestions 
       add constraint FKaoqobwhgmkf8fu9x78uvdvf9l 
       foreign key (department_id) 
       references departments;

    alter table if exists ai_specialty_suggestions 
       add constraint FK5l0a9onwvspgp7spnx4upoqrv 
       foreign key (patient_id) 
       references patients;

    alter table if exists ai_specialty_suggestions 
       add constraint FKhkuquy8ek8pqrpa5rgkhbmgrd 
       foreign key (ai_chat_session_id) 
       references ai_chat_sessions;

    alter table if exists appointment_slots 
       add constraint FKky6awloppaee0snkrqoat7ogd 
       foreign key (schedule_id) 
       references doctor_schedules;

    alter table if exists appointments 
       add constraint FK7s6sk12lb7298bm0j92j4cdgg 
       foreign key (department_id) 
       references departments;

    alter table if exists appointments 
       add constraint FKmujeo4tymoo98cmf7uj3vsv76 
       foreign key (doctor_id) 
       references doctors;

    alter table if exists appointments 
       add constraint FK8exap5wmg8kmb1g1rx3by21yt 
       foreign key (patient_id) 
       references patients;

    alter table if exists appointments 
       add constraint FKmyaw0q6vm88nedh13msfjtvry 
       foreign key (slot_id) 
       references appointment_slots;

    alter table if exists articles 
       add constraint FKdngksgngrmhwar5uop5wj9lef 
       foreign key (created_by) 
       references users;

    alter table if exists audit_logs 
       add constraint FKjs4iimve3y0xssbtve5ysyef0 
       foreign key (user_id) 
       references users;

    alter table if exists doctor_leave_requests 
       add constraint FKs68wsa7l0qibed04a18xysigy 
       foreign key (approved_by) 
       references users;

    alter table if exists doctor_leave_requests 
       add constraint FKlhprovpn9f7wieej3q4i8fxr5 
       foreign key (doctor_id) 
       references doctors;

    alter table if exists doctors 
       add constraint FKl2mro81neln9topymd898urh1 
       foreign key (department_id) 
       references departments;

    alter table if exists doctors 
       add constraint FKe9pf5qtxxkdyrwibaevo9frtk 
       foreign key (user_id) 
       references users;

    alter table if exists invoice_items 
       add constraint FK46ae0lhu1oqs7cv91fn6y9n7w 
       foreign key (invoice_id) 
       references invoices;

    alter table if exists invoices 
       add constraint FK9lx1n0d1xu2stp70xvwmdbflt 
       foreign key (created_by) 
       references users;

    alter table if exists invoices 
       add constraint FKrpyotno5h237hyoaokuggqqog 
       foreign key (patient_id) 
       references patients;

    alter table if exists lab_request_items 
       add constraint FKlqabsa00v3tt85frg5m5apgrd 
       foreign key (lab_request_id) 
       references lab_requests;

    alter table if exists lab_request_items 
       add constraint FKqfnjgl1ng7akops25fa81abst 
       foreign key (lab_test_id) 
       references lab_tests;

    alter table if exists lab_results 
       add constraint FK7br3axsnbwrk63ccut7x8b73 
       foreign key (lab_request_item_id) 
       references lab_request_items;

    alter table if exists medicine_batches 
       add constraint FKct8x0v7kn2ih4x4divm3blwpl 
       foreign key (imported_by) 
       references users;

    alter table if exists medicine_batches 
       add constraint FKc7xcd7bwmfmmfm24oixxu00a2 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists medicine_batches 
       add constraint FKlds0umb8e6lk2afnbqnmjyy41 
       foreign key (supplier_id) 
       references suppliers;

    alter table if exists medicine_stock_alerts 
       add constraint FKcqfx2b8ktsywwdalkv3mykwxd 
       foreign key (batch_id) 
       references medicine_batches;

    alter table if exists medicine_stock_alerts 
       add constraint FKgtfqhk26hi2ber9of21qfjoq5 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists medicine_stock_alerts 
       add constraint FK2cxekgkt73e5f05emk6r5ppuo 
       foreign key (resolved_by) 
       references users;

    alter table if exists notifications 
       add constraint FK9y21adhxn0ayjhfocscqox7bh 
       foreign key (user_id) 
       references users;

    alter table if exists patients 
       add constraint FK5crb1l6i843y9oe9vneob0uj1 
       foreign key (created_by) 
       references users;

    alter table if exists patients 
       add constraint FKuwca24wcd1tg6pjex8lmc0y7 
       foreign key (user_id) 
       references users;

    alter table if exists payments 
       add constraint FKbh1kwjvw3n5ui0ybbkuub7vlx 
       foreign key (confirmed_by) 
       references users;

    alter table if exists payments 
       add constraint FKrbqec6be74wab8iifh8g3i50i 
       foreign key (invoice_id) 
       references invoices;

    alter table if exists payments 
       add constraint FK56qi76rknbyduj0eo4oqn9sm4 
       foreign key (paid_by) 
       references users;

    alter table if exists prescription_items 
       add constraint FKacx7kmy9ksr443xpn5dccidro 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists prescription_items 
       add constraint FK6uh7tdy2lv6sx34u1365acqsf 
       foreign key (prescription_id) 
       references prescriptions;

    alter table if exists queue_tickets 
       add constraint FK34gfg4i59ydop4fvmaqyiodop 
       foreign key (appointment_id) 
       references appointments;

    alter table if exists queue_tickets 
       add constraint FKo4pvgaqjijac86bg6f8askkwx 
       foreign key (department_id) 
       references departments;

    alter table if exists queue_tickets 
       add constraint FKm55c1jht0ufuuvvfjv2asqt4n 
       foreign key (doctor_id) 
       references doctors;

    alter table if exists queue_tickets 
       add constraint FKr1igl0150hmsbtql82cgaubjj 
       foreign key (patient_id) 
       references patients;

    alter table if exists refunds 
       add constraint FKgeyq9s6afhrp3qwdjuxoh830m 
       foreign key (approved_by) 
       references users;

    alter table if exists refunds 
       add constraint FKpt9ic0j1y6xwlej99wnynvnpy 
       foreign key (payment_id) 
       references payments;

    alter table if exists refunds 
       add constraint FKromle2ugk0ah4khd002ktccc8 
       foreign key (processed_by) 
       references users;

    alter table if exists refunds 
       add constraint FK1normc5g6it6fpqbrklfxmert 
       foreign key (requested_by) 
       references users;

    alter table if exists reviews 
       add constraint FKfhaj6kqx2pjpn6eambt0pa1nm 
       foreign key (appointment_id) 
       references appointments;

    alter table if exists reviews 
       add constraint FKf940sak3s3i21v956bej9y0ii 
       foreign key (doctor_id) 
       references doctors;

    alter table if exists reviews 
       add constraint FKkg4mbcdlujuf6rsml463et0bh 
       foreign key (patient_id) 
       references patients;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists stock_transactions 
       add constraint FKnqdmeuvtq90ehn283er371470 
       foreign key (batch_id) 
       references medicine_batches;

    alter table if exists stock_transactions 
       add constraint FK29pj38gl4qoc3bhsoddgfwwia 
       foreign key (created_by) 
       references users;

    alter table if exists stock_transactions 
       add constraint FKsfyde2wx861sfxuk34n6u3vsf 
       foreign key (medicine_id) 
       references medicines;

    alter table if exists system_settings 
       add constraint FKda4dsfh0rkqhmq0bo7plxiqm3 
       foreign key (updated_by) 
       references users;

    alter table if exists user_roles 
       add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 
       foreign key (role_id) 
       references roles;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
